export const ACTION_TYPES = {
	CHANGE_SEARCH_FIELD: 'CHANGE_SEARCH_FIELD',
	FETCH_USERS_START: 'FETCH_USERS_START',
	FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
	FETCH_USERS_FAILED: 'FETCH_USERS_FAILED'
};
